version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # Before starting Gunicorn, collect static into /app/staticfiles
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    # Expose only to other services (nginx). Do NOT publish 8000 on the host.
    expose:
      - "8000"
    volumes:
      - static_volume:/app/staticfiles
      - .:/app   # keep project code mounted for migrations, etc.
    depends_on:
      - bot

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - .env
    volumes:
      - .:/app   # so bot.py sees your code and settings

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      # Mount your cert/key from the VM into the container:
      - /home/ubuntu/certs/server.crt:/etc/nginx/certs/server.crt:ro
      - /home/ubuntu/certs/server.key:/etc/nginx/certs/server.key:ro
      - ./dashboard_app/static/:/app/dashboard_app/static/:ro
      # Mount our custom nginx.conf:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

      # Share the staticfiles volume so Nginx can serve /static/ itself:
      - static_volume:/app/staticfiles
    restart: always

volumes:
  static_volume:
