# Generated by Django 4.2.21 on 2025-05-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('has_unread', models.BooleanField(default=False)),
            ],
        ),
    ]
